version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tsul-feedback-bot
    restart: always
    volumes:
      - ./bot.js:/app/bot.js
      - ./data:/app/data
      - ./stats.json:/app/stats.json
      - ./bot.log:/app/bot.log
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - TZ=Asia/Tashkent
